version: '3'

services:
  redis:
    image: 'redis:3.2.4'
    container_name: 'techbookfest7-example-redis'
    ports:
      - '6379:6379'
    networks: 
      - techbookfest7

networks:
  techbookfest7:
    external: true