version: '3'

services:
  app:
    build: .
    container_name: 'techbookfest7-example-go-api'
    volumes:
      - ./:/go/src/app
    ports:
      - '8080:8080'
    command: 'go run main.go'
    networks: 
      - techbookfest7

networks:
  techbookfest7:
    external: true